"""
Extended activity seed data for trip planning.
Imported by seed_activity_packages.py
"""

EXTRA_ACTIVITIES = {
    "Đà Lạt": [
        {
            "name": "Langbiang - Leo núi ngắm bình minh",
            "description": "Trekking lên đỉnh Langbiang, ngắm bình minh và toàn cảnh cao nguyên.",
            "time_slot": "morning",
            "category": "adventure",
            "duration_hours": 4.0,
            "price": 250000,
            "difficulty": "moderate",
            "location": "Núi Langbiang, Lac Duong",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Huong dan vien", "Nuoc uong", "Bao hiem"],
        },
        {
            "name": "Dinh Bao Dai - Tham quan di tich",
            "description": "Kham pha dinh thu cuoi cung cua vua Bao Dai voi kien truc Phap co.",
            "time_slot": "morning",
            "category": "culture",
            "duration_hours": 2.0,
            "price": 70000,
            "difficulty": "easy",
            "location": "Dinh III Bao Dai, Phuong 10",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ve tham quan", "Huong dan"],
        },
        {
            "name": "Happy Hill - Check-in view doi",
            "description": "Diem check-in view doi voi cau treo, vuon hoa va quan ca phe view dep.",
            "time_slot": "afternoon",
            "category": "relax",
            "duration_hours": 2.0,
            "price": 90000,
            "difficulty": "easy",
            "location": "Happy Hill, Ward 7",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ve vao cua", "1 ly nuoc"],
        },
        {
            "name": "Lang farm - Vuon thu mini",
            "description": "Cho tre em va gia dinh, cho suc, tho, cu va trai nghiem nong trai.",
            "time_slot": "afternoon",
            "category": "nature",
            "duration_hours": 2.5,
            "price": 120000,
            "difficulty": "easy",
            "location": "Lang Farm, Ward 7",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ve tham quan", "Thuc an cho dong vat"],
        },
        {
            "name": "Quang truong Lam Vien - Dao pho dem",
            "description": "Di bo quanh ho Xuan Huong, thuong thuc sua dau nanh va dac san dem.",
            "time_slot": "evening",
            "category": "food",
            "duration_hours": 2.0,
            "price": 80000,
            "difficulty": "easy",
            "location": "Quang truong Lam Vien",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Voucher an uong 50k"],
        },
        {
            "name": "Nha hang view doi - Buffet lau",
            "description": "Buffet lau bo va hai san voi view nhin toan thanh pho ve dem.",
            "time_slot": "evening",
            "category": "food",
            "duration_hours": 2.0,
            "price": 220000,
            "difficulty": "easy",
            "location": "Da Lat View Restaurant",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Buffet lau", "Nuoc uong"],
        },
    ],
    "Hội An": [
        {
            "name": "An Bang Beach - Yoga buoi sang",
            "description": "Tap yoga tren bo bien An Bang voi huong dan vien, tan huong buoi sang yen binh.",
            "time_slot": "morning",
            "category": "relax",
            "duration_hours": 2.0,
            "price": 150000,
            "difficulty": "easy",
            "location": "An Bang Beach",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Tha yoga", "Nuoc detox"],
        },
        {
            "name": "Rung dau nai - Xe dap sinh thai",
            "description": "Dap xe qua rung dau nai, ngam dong co va lang que Hoi An.",
            "time_slot": "morning",
            "category": "nature",
            "duration_hours": 3.0,
            "price": 180000,
            "difficulty": "moderate",
            "location": "Cam Thanh, Hoi An",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Xe dap", "Huong dan", "Nuoc uong"],
        },
        {
            "name": "Reaching Out Tea House - Tra moc",
            "description": "Trai nghiem phong tra im lang, thuong thuc tra thu cong va banh ngot.",
            "time_slot": "afternoon",
            "category": "relax",
            "duration_hours": 1.5,
            "price": 120000,
            "difficulty": "easy",
            "location": "Reaching Out Tea House, Old Town",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Set tra", "Banh"],
        },
        {
            "name": "Basket Boat - Thung chai song Thu Bon",
            "description": "Di thuyen thung chai, xem mua roi va choi tro danh ca.",
            "time_slot": "afternoon",
            "category": "adventure",
            "duration_hours": 2.0,
            "price": 200000,
            "difficulty": "easy",
            "location": "Cam Thanh Coconut Village",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Thuyen thung", "Mu non la"],
        },
        {
            "name": "Lop lam den long - DIY workshop",
            "description": "Tu tay lam den long truyen thong va mang ve lam qua luu niem.",
            "time_slot": "evening",
            "category": "culture",
            "duration_hours": 1.5,
            "price": 150000,
            "difficulty": "easy",
            "location": "Lantern Workshop, Old Town",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Nguyen lieu", "Huong dan", "San pham mang ve"],
        },
        {
            "name": "Nha hang ben song - Set Cao Lau",
            "description": "Thuong thuc Cao Lau, Mi Quang va banh bao banh vac tai nha hang ven song.",
            "time_slot": "evening",
            "category": "food",
            "duration_hours": 1.5,
            "price": 160000,
            "difficulty": "easy",
            "location": "Song Hoai Riverside",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Set am thuc dac san"],
        },
    ],
    "Nha Trang": [
        {
            "name": "Tour 4 dao - Hon Mun Hon Tam",
            "description": "Tour tham quan 4 dao, tam bien va an trua hai san tren tau.",
            "time_slot": "morning",
            "category": "adventure",
            "duration_hours": 6.0,
            "price": 550000,
            "difficulty": "moderate",
            "location": "Cang Vinh Truong, Nha Trang",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Tau ca toc", "Bua trua", "Do lan", "Huong dan"],
        },
        {
            "name": "Institute Oceanography - Thuy vien",
            "description": "Tham quan Vien Hai duong hoc, xem ca map va san vat bien.",
            "time_slot": "morning",
            "category": "culture",
            "duration_hours": 2.0,
            "price": 80000,
            "difficulty": "easy",
            "location": "Institute of Oceanography",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ve tham quan"],
        },
        {
            "name": "Vinpearl Land - Cong vien nuoc",
            "description": "Tron choi cong vien nuoc va tàu luon tren dao Hon Tre.",
            "time_slot": "afternoon",
            "category": "adventure",
            "duration_hours": 4.0,
            "price": 700000,
            "difficulty": "easy",
            "location": "Vinpearl, Hon Tre",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ve cong vien", "Cap treo"],
        },
        {
            "name": "Spa Sen - Massage va xong hoi",
            "description": "Massage body va xong hoi thao duoc sau buoi di bien.",
            "time_slot": "afternoon",
            "category": "relax",
            "duration_hours": 2.0,
            "price": 350000,
            "difficulty": "easy",
            "location": "Sen Spa, Tran Phu",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Massage 90 phut", "Tra thao moc"],
        },
        {
            "name": "Skylight rooftop - Bar view bien",
            "description": "Ngam hoang hon va nghe nhac tai rooftop bar cao nhat Nha Trang.",
            "time_slot": "evening",
            "category": "relax",
            "duration_hours": 2.0,
            "price": 180000,
            "difficulty": "easy",
            "location": "Skylight Nha Trang",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["1 cocktail", "Entry fee"],
        },
        {
            "name": "Lau nuong - BBQ hai san",
            "description": "Buffet hai san nuong tai nha hang ven bien Tran Phu.",
            "time_slot": "evening",
            "category": "food",
            "duration_hours": 2.0,
            "price": 250000,
            "difficulty": "easy",
            "location": "Tran Phu Seafood BBQ",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Buffet hai san"],
        },
    ],
    "Sapa": [
        {
            "name": "Love Waterfall - Thac Tinh Yeu",
            "description": "Trekking den thac Tinh Yeu, ngam rung tuyet tung va thien nhien hoang so.",
            "time_slot": "morning",
            "category": "nature",
            "duration_hours": 3.0,
            "price": 120000,
            "difficulty": "moderate",
            "location": "Thac Tinh Yeu, Sapa",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ve tham quan", "Huong dan"],
        },
        {
            "name": "Cho phien Bac Ha - Van hoa dan toc",
            "description": "Tham gia phien cho Bac Ha (cuoi tuan), mua do tho cam va dac san.",
            "time_slot": "morning",
            "category": "culture",
            "duration_hours": 4.0,
            "price": 200000,
            "difficulty": "easy",
            "location": "Cho Bac Ha",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Xe dua don", "Huong dan"],
        },
        {
            "name": "Silver Waterfall - Thac Bac",
            "description": "Tham quan thac Bac cao hon 200m, chup anh tren cau treo.",
            "time_slot": "afternoon",
            "category": "nature",
            "duration_hours": 2.0,
            "price": 70000,
            "difficulty": "easy",
            "location": "Thac Bac, Sapa",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ve tham quan"],
        },
        {
            "name": "Nha tho da Sapa - Kien truc Phap",
            "description": "Tham quan nha tho da co kien truc Phap giua long thi tran.",
            "time_slot": "afternoon",
            "category": "culture",
            "duration_hours": 1.0,
            "price": 0,
            "difficulty": "easy",
            "location": "Nha tho da Sapa",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Mien phi"],
        },
        {
            "name": "Lau ca hoi - Am thuc vung cao",
            "description": "Lau ca hoi tuoi voi rau rung va gia vi Tay Bac dac trung.",
            "time_slot": "evening",
            "category": "food",
            "duration_hours": 1.5,
            "price": 180000,
            "difficulty": "easy",
            "location": "Sapa Town Center",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Set lau ca hoi"],
        },
        {
            "name": "Show van hoa - Mua dan toc",
            "description": "Xem bieu dien mua dan toc Hmong, Dao va uong ruou ngo.",
            "time_slot": "evening",
            "category": "culture",
            "duration_hours": 1.5,
            "price": 150000,
            "difficulty": "easy",
            "location": "Sapa Culture Show",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ve show", "Ruou mung"],
        },
    ],
    "Phú Quốc": [
        {
            "name": "Hon Thom Cable Car - Cap treo bien",
            "description": "Di cap treo bien dai nhat, ngam quan dao Nam Du tu tren cao.",
            "time_slot": "morning",
            "category": "adventure",
            "duration_hours": 3.0,
            "price": 450000,
            "difficulty": "easy",
            "location": "Hon Thom, An Thoi",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ve cap treo khu hoi"],
        },
        {
            "name": "Pepper Farm - Vuon tieu Phu Quoc",
            "description": "Tham quan vuon tieu, tim hieu quy trinh va mua tieu nguyen chat.",
            "time_slot": "morning",
            "category": "culture",
            "duration_hours": 2.0,
            "price": 60000,
            "difficulty": "easy",
            "location": "Khu Tuong Pepper Farm",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Huong dan", "Thu tieu"],
        },
        {
            "name": "Suoi Tranh - Trekking thac nuoc",
            "description": "Trekking trong rung nguyen sinh den thac Suoi Tranh.",
            "time_slot": "afternoon",
            "category": "nature",
            "duration_hours": 3.0,
            "price": 100000,
            "difficulty": "moderate",
            "location": "Suoi Tranh Ecotourism",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ve vao cua", "Huong dan"],
        },
        {
            "name": "VinWonders Phu Quoc - Cong vien",
            "description": "Cong vien giai tri lon voi show nuoc va vung bao ton.",
            "time_slot": "afternoon",
            "category": "adventure",
            "duration_hours": 5.0,
            "price": 750000,
            "difficulty": "easy",
            "location": "VinWonders, Ganh Dau",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ve cong vien", "Show nuoc"],
        },
        {
            "name": "Night market Dinh Cau - Hai san nuong",
            "description": "An hai san tu chon tai cho dem Dinh Cau.",
            "time_slot": "evening",
            "category": "food",
            "duration_hours": 2.0,
            "price": 180000,
            "difficulty": "easy",
            "location": "Dinh Cau Night Market",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Voucher hai san 120k"],
        },
        {
            "name": "Beach club - BBQ & Live music",
            "description": "To chuc BBQ tren bo bien voi nhac song va cocktail.",
            "time_slot": "evening",
            "category": "relax",
            "duration_hours": 2.5,
            "price": 200000,
            "difficulty": "easy",
            "location": "Ong Lang Beach Club",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["BBQ set", "1 drink"],
        },
    ],
    "Đà Nẵng": [
        {
            "name": "Ba Na Hills - Cau Vang & Lang co Phap",
            "description": "Tham quan cau Vang, lang co Phap va vuon hoa tren dinh Ba Na.",
            "time_slot": "morning",
            "category": "culture",
            "duration_hours": 6.0,
            "price": 850000,
            "difficulty": "easy",
            "location": "Ba Na Hills, Hoa Vang",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ve Ba Na", "Cap treo", "Bua trua"],
        },
        {
            "name": "Son Tra Peninsula - Linh Ung Pagoda",
            "description": "Tham quan tu Linh Ung tuong Phat Quan Am cao 67m, ngam toan thanh pho.",
            "time_slot": "morning",
            "category": "spiritual",
            "duration_hours": 3.0,
            "price": 0,
            "difficulty": "easy",
            "location": "Son Tra Peninsula",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Mien phi", "Huong dan"],
        },
        {
            "name": "My Khe Beach - Tam bien buoi sang",
            "description": "Tam bien tai bai bien My Khe tung duoc Forbes bình chon.",
            "time_slot": "morning",
            "category": "relax",
            "duration_hours": 2.0,
            "price": 50000,
            "difficulty": "easy",
            "location": "My Khe Beach",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ghe nam", "O du"],
        },
        {
            "name": "Marble Mountains - Ngu Hanh Son",
            "description": "Leo nui da voi hang dong, chua linh va view bien.",
            "time_slot": "morning",
            "category": "culture",
            "duration_hours": 3.0,
            "price": 120000,
            "difficulty": "moderate",
            "location": "Ngu Hanh Son, Ngu Hanh Son District",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ve tham quan", "Thang may"],
        },
        {
            "name": "Asia Park - Sun Wheel",
            "description": "Vui choi cong vien giai tri va quay Sun Wheel bieu tuong Da Nang.",
            "time_slot": "afternoon",
            "category": "adventure",
            "duration_hours": 4.0,
            "price": 350000,
            "difficulty": "easy",
            "location": "Asia Park, Hai Chau",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ve cong vien", "Sun Wheel"],
        },
        {
            "name": "Han River Cruise - Du thuyen song Han",
            "description": "Di du thuyen song Han ngam cau Rong va cau Song Han ve dem.",
            "time_slot": "afternoon",
            "category": "relax",
            "duration_hours": 2.0,
            "price": 180000,
            "difficulty": "easy",
            "location": "Bo song Han, Da Nang",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ve tau", "Nuoc uong"],
        },
        {
            "name": "Helio Night Market - Am thuc Da Nang",
            "description": "Kham pha cho dem Helio voi banh trang cuon thit heo va hai san.",
            "time_slot": "evening",
            "category": "food",
            "duration_hours": 2.0,
            "price": 120000,
            "difficulty": "easy",
            "location": "Helio Center, Hai Chau",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Voucher an uong 80k"],
        },
        {
            "name": "Dragon Bridge Show - Phun lua",
            "description": "Xem cau Rong phun lua va nuoc vao cuoi tuan.",
            "time_slot": "evening",
            "category": "culture",
            "duration_hours": 1.0,
            "price": 0,
            "difficulty": "easy",
            "location": "Dragon Bridge, Da Nang",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Mien phi"],
        },
        {
            "name": "Rooftop bar - Sky36",
            "description": "Throng thuc cocktail tren tang 36 voi view toan canh Da Nang.",
            "time_slot": "evening",
            "category": "relax",
            "duration_hours": 2.0,
            "price": 200000,
            "difficulty": "easy",
            "location": "Sky36, Novotel Danang",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["1 cocktail welcome"],
        },
    ],
    "Huế": [
        {
            "name": "Dai Noi Hue - Hoang thanh",
            "description": "Tham quan Hoang thanh Hue, di san van hoa the gioi UNESCO.",
            "time_slot": "morning",
            "category": "culture",
            "duration_hours": 3.5,
            "price": 200000,
            "difficulty": "easy",
            "location": "Dai Noi, Hue City",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ve tham quan", "Huong dan"],
        },
        {
            "name": "Lang Tu Duc - Lang vua",
            "description": "Kham pha lang Tu Duc voi kien truc doc dao giua rung thong.",
            "time_slot": "morning",
            "category": "culture",
            "duration_hours": 2.5,
            "price": 150000,
            "difficulty": "easy",
            "location": "Lang Tu Duc, Thuy Xuan",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ve tham quan", "Audio guide"],
        },
        {
            "name": "Song Huong - Thuyen ca Hue",
            "description": "Di thuyen tren song Huong, nghe ca Hue va ngam binh minh.",
            "time_slot": "morning",
            "category": "culture",
            "duration_hours": 2.0,
            "price": 180000,
            "difficulty": "easy",
            "location": "Bo song Huong, Hue",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Thuyen", "Ca Hue"],
        },
        {
            "name": "Thien Mu Pagoda - Chua Thien Mu",
            "description": "Tham quan chua Thien Mu bieu tuong cua co do Hue.",
            "time_slot": "morning",
            "category": "spiritual",
            "duration_hours": 1.5,
            "price": 0,
            "difficulty": "easy",
            "location": "Thien Mu Pagoda, Kim Long",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Mien phi"],
        },
        {
            "name": "Lang Khai Dinh - Kien truc doc dao",
            "description": "Tham quan lang Khai Dinh ket hop kien truc Dong-Tay doc dao.",
            "time_slot": "afternoon",
            "category": "culture",
            "duration_hours": 2.0,
            "price": 150000,
            "difficulty": "easy",
            "location": "Lang Khai Dinh, Chau E",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ve tham quan"],
        },
        {
            "name": "Tam Giang Lagoon - Dam pha",
            "description": "Di thuyen tren dam pha Tam Giang, nghe hat ho va an hai san.",
            "time_slot": "afternoon",
            "category": "nature",
            "duration_hours": 3.0,
            "price": 250000,
            "difficulty": "easy",
            "location": "Tam Giang Lagoon, Thuan An",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Thuyen", "Hai san", "Hat ho"],
        },
        {
            "name": "Lap banh Beo - Lop nau an Hue",
            "description": "Hoc lam banh beo, banh nam, banh loc dac trung xu Hue.",
            "time_slot": "afternoon",
            "category": "food",
            "duration_hours": 2.5,
            "price": 300000,
            "difficulty": "easy",
            "location": "Hue Cooking Class",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Nguyen lieu", "Cong thuc", "Bua an"],
        },
        {
            "name": "Bun bo Hue - Am thuc dac san",
            "description": "Thuong thuc bun bo Hue chinh goc tai quan noi tieng.",
            "time_slot": "evening",
            "category": "food",
            "duration_hours": 1.5,
            "price": 80000,
            "difficulty": "easy",
            "location": "Bun Bo O Phuong, Hue",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Suat bun bo", "Nuoc uong"],
        },
        {
            "name": "Night walking street - Pho di bo",
            "description": "Dao pho di bo ven song Huong, mua do luu niem va an vat.",
            "time_slot": "evening",
            "category": "culture",
            "duration_hours": 2.0,
            "price": 100000,
            "difficulty": "easy",
            "location": "Pho di bo Nguyen Dinh Chieu",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Voucher an vat 60k"],
        },
    ],
    "Vũng Tàu": [
        {
            "name": "Jesus Christ Statue - Tuong Chua Kito",
            "description": "Leo 847 bac len tuong Chua Kito Vua, ngam toan canh Vung Tau.",
            "time_slot": "morning",
            "category": "spiritual",
            "duration_hours": 2.5,
            "price": 0,
            "difficulty": "moderate",
            "location": "Tuong Chua Kito, Vung Tau",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Mien phi"],
        },
        {
            "name": "Back Beach - Tam bien Back Beach",
            "description": "Tam bien va choi the thao bien tai Back Beach.",
            "time_slot": "morning",
            "category": "relax",
            "duration_hours": 3.0,
            "price": 50000,
            "difficulty": "easy",
            "location": "Back Beach, Vung Tau",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ghe nam", "O du"],
        },
        {
            "name": "Ho May - Cap treo & Ho nuoc",
            "description": "Di cap treo len ho May, choi tro tren mat ho va ngam rung.",
            "time_slot": "morning",
            "category": "adventure",
            "duration_hours": 4.0,
            "price": 350000,
            "difficulty": "easy",
            "location": "Ho May, Vung Tau",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Cap treo", "Ve ho May"],
        },
        {
            "name": "Front Beach - Di bo bo bien",
            "description": "Di bo doc bo bien Front Beach, tham quan den Thang Tam.",
            "time_slot": "afternoon",
            "category": "relax",
            "duration_hours": 2.0,
            "price": 0,
            "difficulty": "easy",
            "location": "Front Beach, Vung Tau",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Mien phi"],
        },
        {
            "name": "Binh Chau Hot Spring - Tam khoang",
            "description": "Tam khoang nong tu nhien va xong hoi thao duoc tai Binh Chau.",
            "time_slot": "afternoon",
            "category": "relax",
            "duration_hours": 3.0,
            "price": 280000,
            "difficulty": "easy",
            "location": "Binh Chau Hot Spring",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Tam khoang", "Khan tam"],
        },
        {
            "name": "Seafood market - Hai san tuoi",
            "description": "Chon hai san tuoi tai cho va nau tai nha hang ven bien.",
            "time_slot": "evening",
            "category": "food",
            "duration_hours": 2.0,
            "price": 200000,
            "difficulty": "easy",
            "location": "Cho hai san Vung Tau",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Voucher hai san 150k"],
        },
        {
            "name": "Bai Dua - Ngam hoang hon",
            "description": "Ngam hoang hon tai bai Dua voi view bien tuyet dep.",
            "time_slot": "evening",
            "category": "relax",
            "duration_hours": 1.5,
            "price": 30000,
            "difficulty": "easy",
            "location": "Bai Dua, Vung Tau",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Ghe ngoi"],
        },
        {
            "name": "Night market - Am thuc dem",
            "description": "Kham pha am thuc dem Vung Tau: banh khot, oc, va hai san nuong.",
            "time_slot": "evening",
            "category": "food",
            "duration_hours": 2.0,
            "price": 120000,
            "difficulty": "easy",
            "location": "Cho dem Vung Tau",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["Voucher an uong 80k"],
        },
        {
            "name": "Bar ven bien - Live music",
            "description": "Thu gian tai bar ven bien voi nhac song va cocktail.",
            "time_slot": "evening",
            "category": "relax",
            "duration_hours": 2.0,
            "price": 150000,
            "difficulty": "easy",
            "location": "Rooftop Bar Vung Tau",
            "image_url": "https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg",
            "included_services": ["1 cocktail"],
        },
    ],
}
