"""
Dataset tĩnh các lễ hội văn hóa TIÊU BIỂU THẾ GIỚI — "lưới an toàn" khi Wikidata SPARQL
bị rate-limit (429) hoặc downtime. Được merge vào place_suggestion_service.
get_local_festivals() cùng Wikidata (primary) + Nager.Date (public holidays).
Dữ liệu mở (tổng hợp kiến thức phổ biến / Wikipedia), ảnh Wikimedia Commons (CC).
`month` = tháng DƯƠNG lịch xấp xỉ (lễ theo âm/Hồi lịch ghi rõ trong `note`).
"""
from typing import Any, Dict, List, Optional

# Mỗi mục: name, country_code (ISO2 hoặc "" = quốc tế), country_label, month,
#   months (tuỳ chọn), location, description, note (âm lịch / ghi chú), image_url.
WORLD_FESTIVALS: List[Dict[str, Any]] = [
    {
        "name": "Mùa hoa anh đào (Sakura)",
        "country_code": "JP",
        "country_label": "Nhật Bản",
        "month": 3,
        "months": [4],
        "location": "Tokyo / Kyoto",
        "description": "Mùa hoa anh đào nở hồng khắp các công viên và bờ sông, lễ ngắm hoa (hanami) lâu đời của người Nhật.",
        "note": "Mùa xuân (tháng 3–4)",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Sakura_and_Moss_Pink_-_%E6%A1%9C%28%E3%81%95%E3%81%8F%E3%82%89%29%E3%81%A8%E8%8A%9D%E6%A1%9C%28%E3%81%97%E3%81%B0%E3%81%96%E3%81%8F%E3%82%89%29.jpg/1280px-Sakura_and_Moss_Pink_-_%E6%A1%9C%28%E3%81%95%E3%81%8F%E3%82%89%29%E3%81%A8%E8%8A%9D%E6%A1%9C%28%E3%81%97%E3%81%B0%E3%81%96%E3%81%8F%E3%82%89%29.jpg",
    },
    {
        "name": "Hanami — Ngắm hoa anh đào",
        "country_code": "JP",
        "country_label": "Nhật Bản",
        "month": 3,
        "months": [4],
        "location": "Khắp Nhật Bản",
        "description": "Truyền thống dã ngoại dưới tán hoa anh đào cùng gia đình, bạn bè.",
        "note": "Tháng 3–4",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/2/2a/Castle_Himeji_sakura02.jpg",
    },
    {
        "name": "Gion Matsuri",
        "country_code": "JP",
        "country_label": "Nhật Bản",
        "month": 7,
        "location": "Kyoto",
        "description": "Lễ hội linh đình nhất Kyoto kéo dài cả tháng, nổi bật với rước xe Yamaboko.",
        "note": "Toàn tháng 7",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Yoiyama_-_The_Gion_Festival_-_July_14%2C_2008.jpg/1280px-Yoiyama_-_The_Gion_Festival_-_July_14%2C_2008.jpg",
    },
    {
        "name": "Obon (Lễ hội O-bon)",
        "country_code": "JP",
        "country_label": "Nhật Bản",
        "month": 8,
        "location": "Khắp Nhật Bản",
        "description": "Lễ hội Phật giáo tưởng nhớ tổ tiên, có điệu múa Bon Odori và thả đèn hoa đăng.",
        "note": "Tháng 7 âm lịch",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/f/f1/Osurasma%2C_or_praying_a_soul_out_of_purgatory-J._M._W._Silver.jpg",
    },
    {
        "name": "Lễ hội tuyết Sapporo",
        "country_code": "JP",
        "country_label": "Nhật Bản",
        "month": 2,
        "location": "Sapporo (Hokkaido)",
        "description": "Hàng trăm tượng tuyết, điêu khắc băng khổng lồ thu hút hàng triệu khách.",
        "note": "Đầu tháng 2",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/SapporoFestival8.JPG/1280px-SapporoFestival8.JPG",
    },
    {
        "name": "Aomori Nebuta Matsuri",
        "country_code": "JP",
        "country_label": "Nhật Bản",
        "month": 8,
        "location": "Aomori",
        "description": "Lễ hội rước đèn hình chiến binh khổng lồ, di sản văn hóa phi vật thể.",
        "note": "Đầu tháng 8",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Aomori_Nebuta_Festival_Float_August_2006.jpg/1280px-Aomori_Nebuta_Festival_Float_August_2006.jpg",
    },
    {
        "name": "Tết Nguyên Đán Trung Quốc",
        "country_code": "CN",
        "country_label": "Trung Quốc",
        "month": 2,
        "months": [1, 2],
        "location": "Khắp Trung Quốc",
        "description": "Đón năm mới âm lịch với màu đỏ, múa lân, pháo hoa — lễ hội lớn nhất năm.",
        "note": "Tháng Giêng âm lịch",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Kung_Hei_Fat_Choi%21_%286834861529%29.jpg/1280px-Kung_Hei_Fat_Choi%21_%286834861529%29.jpg",
    },
    {
        "name": "Tết Nguyên Tiêu (Lễ hội đèn lồng)",
        "country_code": "CN",
        "country_label": "Trung Quốc",
        "month": 2,
        "location": "Khắp Trung Quốc",
        "description": "Rước đèn lồng, ăn bánh trôi nước — kết thúc mùa Tết.",
        "note": "Rằm tháng Giêng âm lịch",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Lantern_Festival_in_Taiwan_at_night_5.jpg/1280px-Lantern_Festival_in_Taiwan_at_night_5.jpg",
    },
    {
        "name": "Tết Đoan Ngọ (Đua thuyền rồng)",
        "country_code": "CN",
        "country_label": "Trung Quốc",
        "month": 6,
        "location": "Khắp Trung Quốc",
        "description": "Đua thuyền rồng, ăn bánh chưng ngọt để tưởng nhớ Khuất Nguyên.",
        "note": "Mùng 5 tháng 5 âm lịch",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/6/6a/Qing_Dynasty_Dragon_Boat_Festival.jpg",
    },
    {
        "name": "Diwali — Lễ hội ánh sáng",
        "country_code": "IN",
        "country_label": "Ấn Độ",
        "month": 11,
        "months": [10],
        "location": "Khắp Ấn Độ",
        "description": "Lễ hội Hindu lớn nhất, thắp hàng triệu ngọn đèn chiến thắng ánh sáng trước bóng tối.",
        "note": "Tháng Kartik (10–11 dương)",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/The_Rangoli_of_Lights.jpg/1280px-The_Rangoli_of_Lights.jpg",
    },
    {
        "name": "Holi — Lễ hội màu sắc",
        "country_code": "IN",
        "country_label": "Ấn Độ",
        "month": 3,
        "location": "Bắc Ấn (Mathura)",
        "description": "Lễ hội mùa xuân Hindu, ném bột màu tưng bừng.",
        "note": "Tháng Phalguna (tháng 3 dương)",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Holi_Celebration_Huranga.jpg/1280px-Holi_Celebration_Huranga.jpg",
    },
    {
        "name": "Hội chợ lạc đà Pushkar",
        "country_code": "IN",
        "country_label": "Ấn Độ",
        "month": 11,
        "location": "Pushkar (Rajasthan)",
        "description": "Hội chợ lạc đà, gia súc và văn hóa Rajasthan giữa sa mạc.",
        "note": "Tháng 11",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/b7/%28A%29_Camel_Pushkar_fair.jpg",
    },
    {
        "name": "Songkran — Tết nước",
        "country_code": "TH",
        "country_label": "Thái Lan",
        "month": 4,
        "location": "Khắp Thái Lan",
        "description": "Đón năm mới Thái Lan bằng trận ném nước tưng bừng khắp nơi.",
        "note": "13–15/4",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Songkran_Day_%40_Chiangmai_Wall.jpg/1280px-Songkran_Day_%40_Chiangmai_Wall.jpg",
    },
    {
        "name": "Loy Krathong",
        "country_code": "TH",
        "country_label": "Thái Lan",
        "month": 11,
        "location": "Khắp Thái Lan",
        "description": "Thả krathong (bè hoa) xuống sông để tạ thần nước.",
        "note": "Rằm tháng 12 âm lịch Thái",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/bd/Thai_people_setting_their_candle-lit_krathongs_in_the_Ping_river_at_night_during_Loy_Krathong_2015-10_%2822715933524%29.jpg",
    },
    {
        "name": "Yi Peng — Thả đèn trời",
        "country_code": "TH",
        "country_label": "Thái Lan",
        "month": 11,
        "location": "Chiang Mai",
        "description": "Thả hàng nghìn đèn trời lồng lộng trên bầu trời Chiang Mai.",
        "note": "Rằm tháng 2 âm lịch Thái",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/0/04/LK_03_loy_krathong_yi_peng_san_sai.jpg",
    },
    {
        "name": "Ngày Quốc khánh Hoa Kỳ",
        "country_code": "US",
        "country_label": "Hoa Kỳ",
        "month": 7,
        "location": "Washington / New York",
        "description": "Kỷ niệm độc lập 4/7 với pháo hoa, diễu hành và BBQ.",
        "note": "4/7",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Fourth_of_July_fireworks_behind_the_Washington_Monument%2C_1986.jpg/1280px-Fourth_of_July_fireworks_behind_the_Washington_Monument%2C_1986.jpg",
    },
    {
        "name": "Mardi Gras",
        "country_code": "US",
        "country_label": "Hoa Kỳ",
        "month": 2,
        "months": [3],
        "location": "New Orleans",
        "description": "Lễ hội hóa trang đường phố lớn nhất nước Mỹ.",
        "note": "Tháng 2 (trước Mùa Chay)",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/KosmicFrenchmenPurpleFaceMardiGras2009.JPG/1280px-KosmicFrenchmenPurpleFaceMardiGras2009.JPG",
    },
    {
        "name": "Coachella Valley Music Festival",
        "country_code": "US",
        "country_label": "Hoa Kỳ",
        "month": 4,
        "location": "Indio (California)",
        "description": "Lễ hội âm nhạc và nghệ thuật lớn, thu hút sao quốc tế.",
        "note": "Tháng 4 (2 cuối tuần)",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Coachella18W1-18_%2842058161311%29.jpg/1280px-Coachella18W1-18_%2842058161311%29.jpg",
    },
    {
        "name": "Halloween",
        "country_code": "",
        "country_label": "",
        "month": 10,
        "location": "Quốc tế",
        "description": "Đêm hóa trang ma quái 'Trick or Treat' cho trẻ em.",
        "note": "31/10",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/a/a2/Jack-o%27-Lantern_2003-10-31.jpg",
    },
    {
        "name": "Burning Man",
        "country_code": "US",
        "country_label": "Hoa Kỳ",
        "month": 9,
        "location": "Black Rock (Nevada)",
        "description": "Lễ hội nghệ thuật 'thành phố tự do' giữa sa mạc, kết thúc bằng đốt người rơm.",
        "note": "Tháng 9",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Temple_du_Burning_Man_2016.jpg/1280px-Temple_du_Burning_Man_2016.jpg",
    },
    {
        "name": "Carnival Rio de Janeiro",
        "country_code": "BR",
        "country_label": "Brazil",
        "month": 2,
        "months": [3],
        "location": "Rio de Janeiro",
        "description": "Lễ hội carnival hoành tráng nhất thế giới với trường diễn samba.",
        "note": "Tháng 2",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Desfile_Portela_2014_%28906185%29.jpg/1280px-Desfile_Portela_2014_%28906185%29.jpg",
    },
    {
        "name": "La Tomatina",
        "country_code": "ES",
        "country_label": "Tây Ban Nha",
        "month": 8,
        "location": "Buñol (Valencia)",
        "description": "Lễ hội ném cà chua tưng bừng khắp phố.",
        "note": "Cuối tháng 8",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Bu%C3%B1ol._Castillo._Vistas.jpg/1280px-Bu%C3%B1ol._Castillo._Vistas.jpg",
    },
    {
        "name": "San Fermín (Chạy bò Pamplona)",
        "country_code": "ES",
        "country_label": "Tây Ban Nha",
        "month": 7,
        "location": "Pamplona",
        "description": "Lễ hội chạy trước đàn bò rống qua các con phố.",
        "note": "6–14/7",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Sanfermines_Vaquillas_Pamplona_08.jpg/1280px-Sanfermines_Vaquillas_Pamplona_08.jpg",
    },
    {
        "name": "Las Fallas",
        "country_code": "ES",
        "country_label": "Tây Ban Nha",
        "month": 3,
        "location": "Valencia",
        "description": "Đốt các tượng giấy khổng lồ mừng mùa xuân.",
        "note": "15–19/3",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/2/23/Natura_Mare_%282%29.jpg",
    },
    {
        "name": "Oktoberfest",
        "country_code": "DE",
        "country_label": "Đức",
        "month": 9,
        "months": [10],
        "location": "Munich",
        "description": "Lễ hội bia lớn nhất thế giới, kéo dài hơn 2 tuần.",
        "note": "Tháng 9–10",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/O%27zapft_is%21_M%C3%BCnchens_5_Jahreszeit_hat_begonnen_-_O%27zapft_is%21_Munich_5_season%2C_the_Oktoberfest_has_begun_%289855483374%29.jpg/1280px-O%27zapft_is%21_M%C3%BCnchens_5_Jahreszeit_hat_begonnen_-_O%27zapft_is%21_Munich_5_season%2C_the_Oktoberfest_has_begun_%289855483374%29.jpg",
    },
    {
        "name": "Chợ Giáng sinh",
        "country_code": "",
        "country_label": "",
        "month": 12,
        "location": "Đức / Châu Âu",
        "description": "Các khu chợ mùa đông lung linh với thức uống nóng và đồ thủ công.",
        "note": "Tháng 12",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/8/8d/Christkindlesmarkt_nuernberg.jpg",
    },
    {
        "name": "Lễ hội hóa trang Venice",
        "country_code": "IT",
        "country_label": "Ý",
        "month": 2,
        "months": [3],
        "location": "Venice",
        "description": "Lễ hội hóa trang cổ kính với mặt nạ và trang phục lộng lẫy.",
        "note": "Tháng 2",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Venice_Carnival_-_Masked_Lovers_%282010%29.jpg/1280px-Venice_Carnival_-_Masked_Lovers_%282010%29.jpg",
    },
    {
        "name": "Palio di Siena",
        "country_code": "IT",
        "country_label": "Ý",
        "month": 8,
        "months": [7],
        "location": "Siena",
        "description": "Cuộc đua ngựa lịch sử giữa các khu phố Siena.",
        "note": "Tháng 7 & 8",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/f/f1/Palio_di_Siena_2008_%282%29.jpg",
    },
    {
        "name": "Ngày Quốc khánh Pháp",
        "country_code": "FR",
        "country_label": "Pháp",
        "month": 7,
        "location": "Paris",
        "description": "Kỷ niệm Cách mạng Pháp 14/7 với diễu hành và pháo hoa tháp Eiffel.",
        "note": "14/7",
        "image_url": "https://upload.wikimedia.org/wikipedia/en/thumb/1/16/Feu_d%27artifice_du_14_juillet_2017_depuis_le_champ_de_Mars_%C3%A0_Paris%2C_devant_la_Tour_Eiffel%2C_Bastille_day_2017_%2835118978683%29.jpg/1280px-Feu_d%27artifice_du_14_juillet_2017_depuis_le_champ_de_Mars_%C3%A0_Paris%2C_devant_la_Tour_Eiffel%2C_Bastille_day_2017_%2835118978683%29.jpg",
    },
    {
        "name": "Liên hoan phim Cannes",
        "country_code": "FR",
        "country_label": "Pháp",
        "month": 5,
        "location": "Cannes",
        "description": "Liên hoan phim danh giá nhất thế giới.",
        "note": "Tháng 5",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/c/c2/Patchwork-Cannes-2.jpg",
    },
    {
        "name": "Carnival Nice",
        "country_code": "FR",
        "country_label": "Pháp",
        "month": 2,
        "months": [3],
        "location": "Nice",
        "description": "Lễ hội hoa và xe hoa lớn Riviera.",
        "note": "Tháng 2",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Floats_at_the_2010_Nice_carnaval.JPG/1280px-Floats_at_the_2010_Nice_carnaval.JPG",
    },
    {
        "name": "Đêm Guy Fawkes",
        "country_code": "GB",
        "country_label": "Anh",
        "month": 11,
        "location": "London",
        "description": "Đốt pháo hoa và hình nộm để kỷ niệm sự kiện 1605.",
        "note": "5/11",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Windsor_castle_guyfawkesnight1776.jpg/1280px-Windsor_castle_guyfawkesnight1776.jpg",
    },
    {
        "name": "Notting Hill Carnival",
        "country_code": "GB",
        "country_label": "Anh",
        "month": 8,
        "location": "London",
        "description": "Lễ hội đường phố lớn nhất châu Âu, văn hóa vùng Caribbean.",
        "note": "Tháng 8 (cuối)",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Notting_Hill_Carnival_2018_%283%29.jpg/1280px-Notting_Hill_Carnival_2018_%283%29.jpg",
    },
    {
        "name": "Edinburgh Festival Fringe",
        "country_code": "GB",
        "country_label": "Anh",
        "month": 8,
        "location": "Edinburgh",
        "description": "Lễ hội nghệ thuật biểu diễn lớn nhất thế giới.",
        "note": "Tháng 8",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Edinburgh_Fringe_037.jpg/1280px-Edinburgh_Fringe_037.jpg",
    },
    {
        "name": "Ngày người chết (Día de los Muertos)",
        "country_code": "MX",
        "country_label": "Mexico",
        "month": 11,
        "location": "Mexico",
        "description": "Lễ hội tưởng nhớ người quá cố đầy màu sắc, di sản UNESCO.",
        "note": "1–2/11",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Catrina_3.jpg/1280px-Catrina_3.jpg",
    },
    {
        "name": "Cinco de Mayo",
        "country_code": "MX",
        "country_label": "Mexico",
        "month": 5,
        "location": "Puebla",
        "description": "Kỷ niệm chiến thắng Puebla trước quân Pháp (1862).",
        "note": "5/5",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/c/c0/Batalla_de_Puebla.png",
    },
    {
        "name": "Lễ hội bùn Boryeong",
        "country_code": "KR",
        "country_label": "Hàn Quốc",
        "month": 7,
        "location": "Boryeong",
        "description": "Lễ hội bùn tắm với các trò chơi và mỹ phẩm bùn.",
        "note": "Tháng 7",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Mud_Fest_2008_%282679028799%29.jpg/1280px-Mud_Fest_2008_%282679028799%29.jpg",
    },
    {
        "name": "Chuseok (Tết đoàn viên Hàn Quốc)",
        "country_code": "KR",
        "country_label": "Hàn Quốc",
        "month": 9,
        "months": [10],
        "location": "Khắp Hàn Quốc",
        "description": "Tết thu tưởng nhớ tổ tiên, tương tự Trung Thu.",
        "note": "Tháng 8 âm lịch Hàn",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Songpyeon.jpg/1280px-Songpyeon.jpg",
    },
    {
        "name": "Ngày Quốc vương Hà Lan (Koningsdag)",
        "country_code": "NL",
        "country_label": "Hà Lan",
        "month": 4,
        "location": "Amsterdam",
        "description": "Sinh nhật quốc vương — cả nước mặc cam và mở chợ trời.",
        "note": "27/4",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/4/43/Amsterdam%27s_Canals.jpg",
    },
    {
        "name": "Vivid Sydney",
        "country_code": "AU",
        "country_label": "Úc",
        "month": 6,
        "months": [5],
        "location": "Sydney",
        "description": "Lễ hội ánh sáng, âm nhạc và ý tưởng trên cảng Sydney.",
        "note": "Tháng 5–6",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Vivid_Sydney_2024_-_Bright_Lights_Big_City.jpg/1280px-Vivid_Sydney_2024_-_Bright_Lights_Big_City.jpg",
    },
    {
        "name": "Inti Raymi (Lễ hội Mặt Trời)",
        "country_code": "PE",
        "country_label": "Peru",
        "month": 6,
        "location": "Cusco",
        "description": "Lễ hội tôn vinh Mặt Trời của người Inca tại pháo đài Sacsayhuamán.",
        "note": "24/6",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Inti_Raymi.jpg/1280px-Inti_Raymi.jpg",
    },
    {
        "name": "Liên hoan Tango Buenos Aires",
        "country_code": "AR",
        "country_label": "Argentina",
        "month": 8,
        "location": "Buenos Aires",
        "description": "Liên hoan tango lớn nhất thế giới.",
        "note": "Tháng 8",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/4/42/Tango_dancers_in_Montevideo.png",
    },
    {
        "name": "Eid al-Fitr (Lễ kết thúc Ramadan)",
        "country_code": "",
        "country_label": "",
        "month": 5,
        "months": [4],
        "location": "Quốc tế (Hồi giáo)",
        "description": "Lễ kết thúc tháng Ramadan với cầu nguyện và lễ hội khắp cộng đồng Hồi giáo.",
        "note": "Dựa trên lịch Hồi giáo",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Eid_al_fitr_photo.jpg/1280px-Eid_al_fitr_photo.jpg",
    },
    {
        "name": "Lễ hội Đêm Trắng",
        "country_code": "RU",
        "country_label": "Nga",
        "month": 6,
        "months": [7],
        "location": "St. Petersburg",
        "description": "Lễ hội nghệ thuật mùa hè khi mặt trời không lặn tại St. Petersburg.",
        "note": "Tháng 6–7",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/a/a9/White_Nights.jpg",
    },
]


def filter_static_world_festivals(
    month: Optional[int] = None,
    country_iso2: str = "",
    is_world: bool = False,
) -> List[Dict[str, Any]]:
    """Lọc dataset tĩnh thế giới theo tháng và mã ISO2 (hoặc tất cả nếu world).
       Chế độ world: trả tất cả. Một nước cụ thể: festival của nước đó (+ festival quốc tế).
    """
    iso = (country_iso2 or "").upper()
    out: List[Dict[str, Any]] = []
    for f in WORLD_FESTIVALS:
        if month:
            months_of = [int(f["month"])]
            extra = f.get("months")
            if isinstance(extra, list):
                months_of += [int(m) for m in extra]
            if int(month) not in months_of:
                continue
        cc = f.get("country_code", "")
        if not is_world and iso and cc and cc != iso:
            continue
        out.append({
            "name": f["name"],
            "description": f.get("description"),
            "start_date": None,
            "end_date": None,
            "location": f.get("location"),
            "image_url": f.get("image_url"),
            "wikidata_url": None,
            "note": f.get("note") or "",
            "country": f.get("country_label") or "",
            "country_code": cc,
            "month": f.get("month"),
            "source": "curated-world",
        })
    return out
